# docker-compose.yml

version: '3.9'
services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - '27000:27017'
    volumes:
      - mongo_data:/data/db

  backend_yoga:
    restart: on-failure
    build: .
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - '5000:5000'

volumes:
  mongo_data:
