# docker-compose.yml

version: '3.9'
services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - '27000:27017'

  backend_nest:
    image: backend_nest
    restart: on-failure
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - '5000:5000'

  frontend_nest:
    image: frontend
    restart: on-failure
    environment:
      BACKEND_URL: backend_nest
    depends_on:
      - backend_nest
    ports:
      - '80:3000'
